---
  - name: Download Zabbix Debian 9 release deb file
    get_url: 
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+stretch_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when: 
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 9

  - name: Download Zabbix Debian 8 release deb file
    get_url: 
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+jessie_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when: 
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 8
    
  - name: Download Zabbix Debian 7 release deb file
    get_url: 
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+wheezy_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 7
    
  - name: Download Zabbix Ubuntu 16 release deb file
    get_url: 
      url: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+xenial_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version']|int == 16

  - name: Download Zabbix Ubuntu 14 release deb file
    get_url: 
      url: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+trusty_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version']|int == 14

  - name: Download Zabbix Ubuntu 18 release deb file
    get_url: 
      url: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version']|int == 18

  - name: apt update Zabbix release in Ubuntu/Debian
    apt: 
      deb: /tmp/zabbix-release_4.0-2.deb
    when: 
      - ansible_facts['os_family'] == "Debian"

  - name: apt-get update
    apt: 
      update_cache: yes
    when: 
      - ansible_facts['os_family'] == "Debian"

  - name: yum install Zabbix release in RHEL or CentOS
    yum: 
      name: http://repo.zabbix.com/zabbix/4.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution'] != "Amazon"

  - name: yum install zabbix release in Amazon Linux
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
    when: 
      - ansible_facts['distribution'] == "Amazon"
      - ansible_facts['distribution_major_version']|int == 1

  - name: yum install zabbix release in Amazon Linux 2
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    when:
      - ansible_distribution == "Amazon"
      - ansible_facts['distribution_major_version']|int == 2
    
  - name: apt install Zabbix agent
    apt: 
      name: zabbix-agent
    when: ansible_os_family == "Debian"

  - name: yum install Zabbix agent
    yum: 
      name: zabbix-agent
    when: ansible_os_family == "RedHat"
