---
  - name: Check installed zabbix agent
    stat: 
      path: /usr/sbin/zabbix_agentd
    register: zabbix_agent_installed
    tags:
      - install
      - upgrade

  - name: Install Zabbix agent
    include_tasks: install.yaml
    when: zabbix_agent_installed.stat.exists == false
    register: install_zabbix_agent
    tags:
      - install

  - name: Configure
    include_tasks: configure.yaml
    when: not install_zabbix_agent.skipped
    register: configure_zabbix

  - name: Configure
    include_tasks: configure.yaml
    when:
      - install_zabbix_agent is succeeded
      - configure_zabbix is undefined
    tags:
      - install

  - name: Upgrade Zabbix agent and Proxy
    include_tasks: upgrade.yaml
    register: upgrade_zabbix
    when:
      - zabbix_agent_installed.stat.exists
      - configure_zabbix is skipped
      - install_zabbix_agent is skipped      

  - name: Upgrade Zabbix agent and Proxy
    include_tasks: upgrade.yaml
    when:
      - zabbix_agent_installed.stat.exists
      - upgrade_zabbix is undefined
    tags:
      - upgrade

  - name: Create log directory
    file:
      path: /var/log/zabbix
      state: directory
      owner: zabbix
      group: zabbix
      mode: 0775
    when: not configure_zabbix.skipped
    register: create_log

  - name: Create log directory
    file:
      path: /var/log/zabbix
      state: directory
      owner: zabbix
      group: zabbix
      mode: 0775
    when:
      - install_zabbix_agent is succeeded
      - create_log is undefined
    tags:
      - install

  - name: Start Zabbix agent service
    service: 
      name: zabbix-agent
      state: started
      enabled: yes
    when: zabbix_agent_installed.stat.exists
    tags:
      - install
      - upgrade

  - name: Check Zabbix Proxy
    stat: 
      path: /usr/sbin/zabbix_proxy
    register: zabbix_proxy_installed
    tags:
      - upgrade
      - start-proxy    

  - name: Start Zabbix proxy
    service: 
      name: zabbix-proxy
      state: started
      enabled: yes
    when: zabbix_proxy_installed.stat.exists
    tags:
      - upgrade
      - start-proxy