---
#- name: Main Zabbix agent install
#  hosts: local # delete
#  become: yes #delete

#  tasks: #delete
  # Add a fast check to speed reconfiguration
  - name: Check installed zabbix agent
    stat: 
      path: /usr/sbin/zabbix_agentd
    register: zabbix_agent_installed

  - name: Install Zabbix agent
    include_tasks: install.yaml
    when: zabbix_agent_installed.stat.exists == "false"
    register: install_zabbix_agent

#  - debug: 
#       msg: "{{ install_zabbix_agent.skipped }}"

  - name: Configure
    include_tasks: configure.yaml
    when: install_zabbix_agent.skipped != true
    register: configure_zabbix

#  - debug:
#       msg: "{{ configure_zabbix }}"

  - name: Update Zabbix agent
    include_tasks: update.yaml
    when: zabbix_agent_installed.stat.exists == "true"

  - name: Create log directory
    file: path=/var/log/zabbix state=directory owner=zabbix group=zabbix mode=0775
    when: configure_zabbix.skipped != true

  - name: Start Zabbix agent service
    service: name=zabbix-agent state=started enabled=yes
    ignore_errors: yes
    register: zabbix_service

  - name: Start Zabbix agent in Centos 7
    shell: pgrep zabbix_agentd || /usr/sbin/zabbix_agentd
    when: zabbix_service is failed

  - name: Check Zabbix Proxy
    stat: 
      path: /usr/sbin/zabbix_proxy
    register: zabbix_proxy_installed    

  - name: Start Zabbix proxy
    service: 
      name: zabbix-proxy
      state: started
      enabled: yes
    ignore_errors: yes
    register: zabbix_proxy_service
    when: zabbix_proxy_installed.stat.exist == "true"

  - name: Start Zabbix proxy in Centos
    shell: pgrep zabbix_proxy || /usr/sbin/zabbix_proxy
    when:
      - zabbix_proxy_service is failed
      - zabbix_proxy_installed.stat.exist == "true"
    ignore_errors: yes
