---
  - name: Check installed zabbix agent
    stat: 
      path: /usr/sbin/zabbix_agentd
    register: zabbix_agent_installed

  - name: Install Zabbix agent
    include_tasks: install.yaml
    when: zabbix_agent_installed.stat.exists == "false"
    register: install_zabbix_agent

  - name: Configure
    include_tasks: configure.yaml
    when: install_zabbix_agent.skipped != true
    register: configure_zabbix

  - name: Update Zabbix agent and Proxy
    include_tasks: update.yaml
    when: zabbix_agent_installed.stat.exists == "true"

  - name: Create log directory
    file: path=/var/log/zabbix state=directory owner=zabbix group=zabbix mode=0775
    when: configure_zabbix.skipped != true

  - name: Start Zabbix agent service
    service: 
      name: zabbix-agent
      state: started
      enabled: yes

  - name: Check Zabbix Proxy
    stat: 
      path: /usr/sbin/zabbix_proxy
    register: zabbix_proxy_installed    

  - name: Start Zabbix proxy
    service: 
      name: zabbix-proxy
      state: started
      enabled: yes
    register: zabbix_proxy_service
    when: zabbix_proxy_installed.stat.exists == "true"
