---
  - tasks:

  - name: Download Zabbix Debian 9 release deb file
    get_url: 
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+​stretch_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when: 
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 9

  - name: Download Zabbix Debian 8 release deb file
    get_url: 
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+​​jessie_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when: 
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 8
    
  - name: Download Zabbix Debian 7 release deb file
    get_url: 
      url: https://repo.zabbix.com/zabbix/4.0/debian/pool/main/z/zabbix-release/zabbix-release_4.0-2+​wheezy_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 7
    
  - name: Download Zabbix Ubuntu 16 release deb file
    get_url: 
      url: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+xenial_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version']|int == 16

  - name: Download Zabbix Ubuntu 14 release deb file
    get_url: 
      url: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+trusty_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version']|int == 14

  - name: Download Zabbix Ubuntu 18 release deb file
    get_url: 
      url: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+bionic_all.deb
      dest: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Ubuntu"
      - ansible_facts['distribution_major_version']|int == 18

  - name: apt update Zabbix release in Ubuntu/Debian
    apt: 
      deb: /tmp/zabbix-release_4.0-2.deb
    when: 
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int != 9
    register: result_zabbix_release

  - name: apt install Zabbix release in Debian 9
    apt: 
      deb: /tmp/zabbix-release_4.0-2.deb
    when:
      - ansible_facts['os_family'] == "Debian"
      - ansible_facts['distribution'] == "Debian"
      - ansible_facts['distribution_major_version']|int == 9
    register: result_zabbix_release

  - name: apt-get update
    apt: 
      update_cache: yes
    when: 
      - ansible_facts['os_family'] == "Debian"
      - result_zabbix_release|changed

  - name: yum install Zabbix release in RHEL or CentOS
    yum: 
      name: http://repo.zabbix.com/zabbix/4.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution'] != "Amazon"

  - name: yum install zabbix release in Amazon Linux
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
    when: 
      - ansible_facts['distribution'] == "Amazon"
      - ansible_facts['distribution_major_version']|int == 1

  - name: yum install zabbix release in Amazon Linux 2
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    when:
      - ansible_distribution == "Amazon"
      - ansible_facts['distribution_major_version']|int == 2
    
  - name: apt upgrade Zabbix agent
    apt: 
      name: zabbix-agent
      state: latest
    when: ansible_facts['os_family'] == "Debian"

  - name: yum upgrade Zabbix agent
    yum: 
      name: zabbix-agent
      state: latest
    when: ansible_facts['os_family'] == "RedHat"
  
  - name: Check Zabbix Proxy
    stat: path=/usr/sbin/zabbix_proxy
    register: zabbix_proxy_installed
  
  - name: Stop service httpd, if started
    service:
      name: zabbix-proxy
      state: stopped
    when: zabbix_proxy_installed.stat.exists
    register: zabbix_proxy_stopped

  - name: Delete zabbix.db
    file:
      path: /var/lib/sqlite/zabbix.db
      state: absent
    when: zabbix_proxy_stopped|changed
    register: delete_zabbixbd

  - name: apt upgrade Zabbix Proxy
    apt:
      name: zabbix-proxy
      state: latest
    when: 
      - delete_zabbixbd|changed
      - ansible_facts['os_family'] == "Debian"

  - name: yun upgrade Zabbix Proxy
    yum:
      name: zabbix-proxy
      state: latest
    when:
      - delete_zabbixbd|changed
      - ansible_facts['os_family'] == "RedHat"
