---
  - name: delete old sources in debian
    file:
      path: /etc/apt/sources.list.d/zabbix.list
      state: absent
    when: ansible_facts['os_family'] == "Debian"

  - name: delete old zabbix release
    apt:
      name: zabbix-release
      state: absent
    when: ansible_facts['os_family'] == "Debian"

  - name: apt update Zabbix release in Ubuntu/Debian
    apt: 
      deb: http://repo.zabbix.com/zabbix/4.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_4.0-2+{{ ansible_facts['distribution_release'] }}_all.deb
    when: ansible_facts['os_family'] == "Debian"

  - name: Add zabbix repo
    apt_repository:
      repo: "{{ item }} http://repo.zabbix.com/zabbix/4.0/{{ ansible_facts['distribution']|lower}} {{ ansible_facts['distribution_release'] }} main"
      state: present
      filename: zabbix
    loop:
      - deb
      - deb-src
    when: ansible_facts['os_family'] == "Debian"

  - name: apt-get update
    apt: 
      update_cache: yes
    when: 
      - ansible_facts['os_family'] == "Debian"

  - name: yum install Zabbix release in RHEL or CentOS
    yum: 
      name: http://repo.zabbix.com/zabbix/4.0/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-4.0-1.el{{ ansible_distribution_major_version }}.noarch.rpm
    when:
      - ansible_facts['os_family'] == "RedHat"
      - ansible_facts['distribution'] != "Amazon"

  - name: yum install zabbix release in Amazon Linux
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/6/x86_64/zabbix-release-4.0-1.el6.noarch.rpm
    when: 
      - ansible_facts['distribution'] == "Amazon"
      - ansible_facts['distribution_major_version']|int == 1

  - name: yum install zabbix release in Amazon Linux 2
    yum:
      name: http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm
    when:
      - ansible_distribution == "Amazon"
      - ansible_facts['distribution_major_version']|int == 2
    
  - name: apt upgrade Zabbix agent
    apt: 
      name: zabbix-agent
      state: latest
      only_upgrade: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: yum upgrade Zabbix agent
    yum: 
      name: zabbix-agent
      state: latest
      only_upgrade: yes
    when: ansible_facts['os_family'] == "RedHat"

  - name: Check Zabbix Proxy
    stat: 
      path: /usr/sbin/zabbix_proxy
    register: zabbix_proxy_installed
  
  - name: Stop service Zabbix Proxy
    service:
      name: zabbix-proxy
      state: stopped
    when: zabbix_proxy_installed.stat.exists
    register: zabbix_proxy_stopped

  - name: Delete zabbix db
    file:
      path: /var/lib/sqlite/zabbix.db
      state: absent
    when: zabbix_proxy_stopped is succeeded

  - name: apt upgrade Zabbix Proxy
    apt:
      name: zabbix-proxy-sqlite3
      state: latest
      only_upgrade: yes
    when: ansible_facts['os_family'] == "Debian"

  - name: yun upgrade Zabbix Proxy
    yum:
      name: zabbix-proxy-sqlite3
      state: latest
      only_upgrade: yes
    when: ansible_facts['os_family'] == "RedHat"